title: riveli.io
description: Trading and technology. Registered in Waalre, the Netherlands.
plugins:
  - jekyll-seo-tag
show_downloads: false
google_analytics: G-4F0WJFSTYQ

company:
  legal_name: riveli.io
  kvk: "89791444"
  vat: "NL004760034B11"
  city: Waalre
  country: The Netherlands
  email: info@riveli.io
